projectId: <gcp-project-id>
region: us-central1
imageUrl: gs://some-gcp-bucket/some-path/some-image.jpeg
promptText: "describe the picture?"
contentGenerationConfig:
  max_output_tokens: 2048   # Range 1-2048
  temperature: 0.4          # Range 0-1 
  top_p: 1                  # Range 0-1  
  top_k: 32                 # Range 1-40
contentSafetyConfig:                    # HARM_BLOCK_THRESHOLD_UNSPECIFIED: 0
  hateSpeechThreshold: 3                # BLOCK_LOW_AND_ABOVE: 1
  dangerousContentThreshold: 3          # BLOCK_MEDIUM_AND_ABOVE (Default): 2
  harasssmentThreshold: 3               # BLOCK_ONLY_HIGH: 3
  sexuallyExplicitThreshold: 3          # BLOCK_NONE: 4